language: java

jdk:
  - oraclejdk10

env:
  - JAVA_VERSION=9
  - JAVA_VERSION=10

addons:
  sonarcloud:
    organization: "benjaminkomen-github"

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Djava.version=$JAVA_VERSION
